language: go
sudo: false
go:
  - "1.12"
before_install:
  - ./tools/install_kustomize.sh
  - ./tools/install_kubebuilder.sh
  - make generate
env:
  - TARGET=fmt
  - TARGET=vet
  - TARGET=unit
script: KUBEBUILDER_ASSETS="$(pwd)/kubebuilder/bin/" make $TARGET
