namePrefix: capm3-

commonLabels:
  cluster.x-k8s.io/provider: "infrastructure-metal3"

bases:
- crd
- webhook # Disable this if you're not using the webhook functionality.
- default

patchesJson6902:
- target: # NOTE: This patch needs to be repeatd for EACH CustomResourceDefinition you have under crd/bases.
    group: apiextensions.k8s.io
    version: v1
    kind: CustomResourceDefinition
    name: metal3clusters.infrastructure.cluster.x-k8s.io
  path: patch_crd_webhook_namespace.yaml
- target:
    group: apiextensions.k8s.io
    version: v1
    kind: CustomResourceDefinition
    name: metal3machines.infrastructure.cluster.x-k8s.io
  path: patch_crd_webhook_namespace.yaml
- target:
    group: apiextensions.k8s.io
    version: v1
    kind: CustomResourceDefinition
    name: metal3machinetemplates.infrastructure.cluster.x-k8s.io
  path: patch_crd_webhook_namespace.yaml
