
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: baremetalmachineproviderspecs.baremetal.cluster.k8s.io
spec:
  group: baremetal.cluster.k8s.io
  names:
    kind: BareMetalMachineProviderSpec
    plural: baremetalmachineproviderspecs
  scope: ""
  validation:
    openAPIV3Schema:
      description: BareMetalMachineProviderSpec holds data that the actuator needs
        to provision and manage a Machine.
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        hostSelector:
          description: HostSelector specifies matching criteria for labels on BareMetalHosts.
            This is used to limit the set of BareMetalHost objects considered for
            claiming for a Machine.
          properties:
            matchExpressions:
              description: Label match expressions that must be true on a chosen BareMetalHost
              items:
                properties:
                  key:
                    type: string
                  operator:
                    description: Operator represents a key/field's relationship to
                      value(s). See labels.Requirement and fields.Requirement for
                      more details.
                    type: string
                  values:
                    items:
                      type: string
                    type: array
                required:
                - key
                - operator
                - values
                type: object
              type: array
            matchLabels:
              additionalProperties:
                type: string
              description: Key/value pairs of labels that must exist on a chosen BareMetalHost
              type: object
          type: object
        image:
          description: Image is the image to be provisioned.
          properties:
            checksum:
              description: Checksum is a md5sum value or a URL to retrieve one.
              type: string
            url:
              description: URL is a location of an image to deploy.
              type: string
          required:
          - checksum
          - url
          type: object
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        userData:
          description: UserData references the Secret that holds user data needed
            by the bare metal operator. The Namespace is optional; it will default
            to the Machine's namespace if not specified.
          properties:
            name:
              description: Name is unique within a namespace to reference a secret
                resource.
              type: string
            namespace:
              description: Namespace defines the space within which the secret name
                must be unique.
              type: string
          type: object
      required:
      - image
      type: object
  version: v1alpha2
  versions:
  - name: v1alpha2
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
